server:
    port: 8081
    sessionTimeout: 30
spring:         
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true
    datasource:
        url: jdbc:mysql://lizhe.name:8088/Lira?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
        min-idle: 5
        max-idle: 10
        max-wait: 10000
        initial-size: 5
mybatis:
    mapperLocations: classpath*:name/lizhe/lira/module/login/dao/mapper/LoginMapper.xml
logging:  
    level:  
        org.mybatis: INFO
